/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Components.Toast.Notifications;
import Functions.Dashboard.ArrayCounter;
import Functions.Dashboard.ChangeActiveButton;
import Functions.Dashboard.Checkout.CheckoutGrouping;
import static Functions.Dashboard.Checkout.CheckoutUpdater.updateCheckout;
import Functions.Dashboard.ComponentInit;
import Functions.Dashboard.Menu.MenuGrouping;
import Functions.Dashboard.MenuButtonClass;
import Functions.Dashboard.Menu.MenuUpdater;
import Functions.MySQL.Database;
import Functions.Utils.Screen;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import java.awt.Point;
import java.util.List;
import java.util.Map;
import javax.swing.JLabel;
/**
 *
 * @author dxrry
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    private ChangeActiveButton changeActiveButton;
    private ComponentInit componentSearch;
    
    private int totalPages;
    private int currentPages = 0;
    private String currentMenuCategories;
    
    private int currentCheckoutPages = 0;
    
    private List<Integer> menuId = null;
    private int[] menuSelected = {};
    
    private JLabel[] componentsMenu;
    private JLabel[] componentsCheckout;
    
    private MenuButtonClass[] componentsMenuButton;
    
    private Integer userAuthLoginId = 0;
    
    public Database db = new Database();
    
    public Dashboard(Integer userAuthLoginId) {
        initComponents();
        FlatLaf.registerCustomDefaultsSource("Components.Toast");
        FlatIntelliJLaf.setup();
        Notifications.getInstance().setJFrame(this);
        
        componentInitSend();
        menuButtonInit();
        
        menuSelected = updateCheckout(
                menuSelected,
                0,
                currentCheckoutPages, 
                componentSearch,
                checkoutButtonPrev,
                checkoutButtonNext
        );
            String fullname = "Five User";
            if(userAuthLoginId != 0) {
                this.userAuthLoginId = userAuthLoginId;
                menuButtonLogin.setText("Log Out");
                fullname = db.getUserFullname(userAuthLoginId);
            }else{
                menuButton5.setVisible(false);
            }
            userNameLabel.setText(fullname);
        
    }
    
    private void menuButtonInit() {
        componentsMenuButton = new MenuButtonClass[] {
            menuButton1,
            menuButton2,
            menuButton3
        };
        ChangeActiveButton newChangeActiveButton = new ChangeActiveButton(componentsMenuButton);
        this.changeActiveButton = newChangeActiveButton;
        changeActiveButtonSend(1);
    }
    private void componentInitSend() {
        componentsMenu = new JLabel[] {
            menuName1, menuName2, menuName3,
            menuPrice1, menuPrice2, menuPrice3,
            menuIcon1, menuIcon2, menuIcon3,
            menuDesc1, menuDesc2, menuDesc3,
            menuBackground1, menuBackground2, menuBackground3
        };
        componentsCheckout = new JLabel[] {
            checkoutIcon1, checkoutIcon2,
            checkoutName1, checkoutName2,
            checkoutPrice1, checkoutPrice2,
            checkoutBackground1, checkoutBackground2,
            checkoutQty1, checkoutQty2,
            checkoutTotalPriceLabel
        };
        ComponentInit menuComponents = new ComponentInit(componentsMenu, componentsCheckout);
        this.componentSearch = menuComponents;
    }
    private void changeActiveButtonSend(Integer buttonIndex) {
        String resultMenuCategories = changeActiveButton.setActiveButton(buttonIndex);
        
        if(currentMenuCategories == null || !currentMenuCategories.equals(resultMenuCategories)) {
            currentPages = 0;
        }
        currentMenuCategories = resultMenuCategories;
        menuId = MenuUpdater.updateMenu(
                componentSearch,
                currentMenuCategories,
                currentPages,
                menuButtonNext,
                menuButtonPrev
        ); 
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonCheckout = new Functions.Dashboard.MenuButtonClass();
        checkoutButtonPrev = new Functions.Dashboard.MenuButtonClass();
        checkoutButtonNext = new Functions.Dashboard.MenuButtonClass();
        menuButtonNext = new Functions.Dashboard.MenuButtonClass();
        menuButton5 = new Functions.Dashboard.MenuButtonClass();
        menuButtonLogin = new Functions.Dashboard.MenuButtonClass();
        menuButtonPrev = new Functions.Dashboard.MenuButtonClass();
        menuButton1 = new Functions.Dashboard.MenuButtonClass();
        menuButton2 = new Functions.Dashboard.MenuButtonClass();
        menuButton3 = new Functions.Dashboard.MenuButtonClass();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        daftarMenuLabel = new javax.swing.JLabel();
        menuPrice3 = new javax.swing.JLabel();
        menuDesc1 = new javax.swing.JLabel();
        menuPrice2 = new javax.swing.JLabel();
        menuIcon1 = new javax.swing.JLabel();
        menuIcon2 = new javax.swing.JLabel();
        menuIcon3 = new javax.swing.JLabel();
        menuName1 = new javax.swing.JLabel();
        menuName2 = new javax.swing.JLabel();
        menuName3 = new javax.swing.JLabel();
        menuDesc2 = new javax.swing.JLabel();
        menuDesc3 = new javax.swing.JLabel();
        menuPrice1 = new javax.swing.JLabel();
        menuBackground1 = new javax.swing.JLabel();
        menuBackground2 = new javax.swing.JLabel();
        menuBackground3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        checkoutQty1 = new javax.swing.JLabel();
        checkoutQty2 = new javax.swing.JLabel();
        checkoutTotalPriceLabel = new javax.swing.JLabel();
        checkoutTotalLabel = new javax.swing.JLabel();
        checkoutIcon1 = new javax.swing.JLabel();
        checkoutIcon2 = new javax.swing.JLabel();
        checkoutName1 = new javax.swing.JLabel();
        checkoutName2 = new javax.swing.JLabel();
        checkoutPrice1 = new javax.swing.JLabel();
        checkoutPrice2 = new javax.swing.JLabel();
        checkoutBackground1 = new javax.swing.JLabel();
        checkoutBackground2 = new javax.swing.JLabel();
        backgroundMainDasboard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonCheckout.setForeground(new java.awt.Color(255, 255, 255));
        buttonCheckout.setText("Check Out");
        buttonCheckout.setColor(new java.awt.Color(255, 189, 36));
        buttonCheckout.setFont(new java.awt.Font("Poppins", 1, 17)); // NOI18N
        buttonCheckout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonCheckout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCheckout.setRadius(35);
        buttonCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCheckoutMouseClicked(evt);
            }
        });
        getContentPane().add(buttonCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 680, 350, 70));

        checkoutButtonPrev.setForeground(new java.awt.Color(153, 153, 153));
        checkoutButtonPrev.setText("Prev");
        checkoutButtonPrev.setColor(new java.awt.Color(200, 18, 22));
        checkoutButtonPrev.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        checkoutButtonPrev.setName("checkoutButtonPrev"); // NOI18N
        checkoutButtonPrev.setRadius(35);
        checkoutButtonPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkoutButtonPrevMouseClicked(evt);
            }
        });
        getContentPane().add(checkoutButtonPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 480, 130, 70));

        checkoutButtonNext.setForeground(new java.awt.Color(255, 255, 255));
        checkoutButtonNext.setText("Next");
        checkoutButtonNext.setColor(new java.awt.Color(200, 18, 22));
        checkoutButtonNext.setFont(new java.awt.Font("Poppins", 1, 17)); // NOI18N
        checkoutButtonNext.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        checkoutButtonNext.setName("checkoutButtonNext"); // NOI18N
        checkoutButtonNext.setRadius(35);
        checkoutButtonNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkoutButtonNextMouseClicked(evt);
            }
        });
        getContentPane().add(checkoutButtonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 480, 130, 70));

        menuButtonNext.setForeground(new java.awt.Color(255, 255, 255));
        menuButtonNext.setText("Next Menu");
        menuButtonNext.setColor(new java.awt.Color(200, 18, 22));
        menuButtonNext.setFont(new java.awt.Font("Poppins", 1, 17)); // NOI18N
        menuButtonNext.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        menuButtonNext.setRadius(35);
        menuButtonNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuButtonNextMouseClicked(evt);
            }
        });
        menuButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonNextActionPerformed(evt);
            }
        });
        getContentPane().add(menuButtonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, 210, 70));

        menuButton5.setForeground(new java.awt.Color(255, 255, 255));
        menuButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons8-document-28.png"))); // NOI18N
        menuButton5.setText("History");
        menuButton5.setColor(new java.awt.Color(255, 189, 36));
        menuButton5.setFont(new java.awt.Font("Poppins", 1, 17)); // NOI18N
        menuButton5.setName("menuButton3"); // NOI18N
        menuButton5.setRadius(35);
        menuButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuButton5MouseClicked(evt);
            }
        });
        menuButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(menuButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 210, 70));

        menuButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        menuButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons8-key-28.png"))); // NOI18N
        menuButtonLogin.setText("Log In");
        menuButtonLogin.setAutoscrolls(true);
        menuButtonLogin.setColor(new java.awt.Color(255, 189, 36));
        menuButtonLogin.setFont(new java.awt.Font("Poppins", 1, 17)); // NOI18N
        menuButtonLogin.setName("menuButton3"); // NOI18N
        menuButtonLogin.setRadius(35);
        menuButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuButtonLoginMouseClicked(evt);
            }
        });
        getContentPane().add(menuButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 210, 70));

        menuButtonPrev.setForeground(new java.awt.Color(153, 153, 153));
        menuButtonPrev.setText("Prev Menu");
        menuButtonPrev.setColor(new java.awt.Color(200, 18, 22));
        menuButtonPrev.setFont(new java.awt.Font("Poppins", 1, 17)); // NOI18N
        menuButtonPrev.setRadius(35);
        menuButtonPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuButtonPrevMouseClicked(evt);
            }
        });
        menuButtonPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonPrevActionPerformed(evt);
            }
        });
        getContentPane().add(menuButtonPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 210, 70));

        menuButton1.setForeground(new java.awt.Color(255, 255, 255));
        menuButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons8-rice-bowl-32.png"))); // NOI18N
        menuButton1.setText("menuButton1");
        menuButton1.setColor(new java.awt.Color(255, 189, 36));
        menuButton1.setFont(new java.awt.Font("Poppins", 1, 17)); // NOI18N
        menuButton1.setName("menuButton1"); // NOI18N
        menuButton1.setRadius(35);
        menuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(menuButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 210, 70));

        menuButton2.setForeground(new java.awt.Color(255, 255, 255));
        menuButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons8-wine-bar-32.png"))); // NOI18N
        menuButton2.setText("menuButton2");
        menuButton2.setColor(new java.awt.Color(255, 189, 36));
        menuButton2.setFont(new java.awt.Font("Poppins", 1, 17)); // NOI18N
        menuButton2.setName("menuButton2"); // NOI18N
        menuButton2.setRadius(35);
        menuButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(menuButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 210, 70));

        menuButton3.setForeground(new java.awt.Color(255, 255, 255));
        menuButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons8-ingredients-32.png"))); // NOI18N
        menuButton3.setText("menuButton3");
        menuButton3.setColor(new java.awt.Color(255, 189, 36));
        menuButton3.setFont(new java.awt.Font("Poppins", 1, 17)); // NOI18N
        menuButton3.setName("menuButton3"); // NOI18N
        menuButton3.setRadius(35);
        menuButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(menuButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 210, 70));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(142, 142, 142));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Hello !");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 200, 40));

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nice to Meet U");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 250, 40));

        userNameLabel.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userNameLabel.setText("FiveUser");
        getContentPane().add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 160, 40));

        daftarMenuLabel.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        daftarMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        daftarMenuLabel.setText("Daftar Menu");
        getContentPane().add(daftarMenuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 250, 40));

        menuPrice3.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        menuPrice3.setForeground(new java.awt.Color(41, 33, 44));
        menuPrice3.setText("menuPrice3");
        menuPrice3.setName("menuPrice3"); // NOI18N
        getContentPane().add(menuPrice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 680, 140, 50));

        menuDesc1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        menuDesc1.setForeground(new java.awt.Color(41, 33, 44));
        menuDesc1.setText("menuDesc1");
        menuDesc1.setName("menuDesc1"); // NOI18N
        getContentPane().add(menuDesc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 640, 160, 50));

        menuPrice2.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        menuPrice2.setForeground(new java.awt.Color(41, 33, 44));
        menuPrice2.setText("menuPrice2");
        menuPrice2.setName("menuPrice2"); // NOI18N
        getContentPane().add(menuPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 680, 140, 50));

        menuIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ItemsMenuIcon.png"))); // NOI18N
        menuIcon1.setName("menuIcon1"); // NOI18N
        getContentPane().add(menuIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, -1, -1));

        menuIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ItemsMenuIcon.png"))); // NOI18N
        menuIcon2.setName("menuIcon2"); // NOI18N
        getContentPane().add(menuIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, -1, -1));

        menuIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ItemsMenuIcon.png"))); // NOI18N
        menuIcon3.setName("menuIcon3"); // NOI18N
        getContentPane().add(menuIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 490, -1, -1));

        menuName1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        menuName1.setForeground(new java.awt.Color(41, 33, 44));
        menuName1.setText("menuName1");
        menuName1.setName("menuName1"); // NOI18N
        getContentPane().add(menuName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 160, 50));

        menuName2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        menuName2.setForeground(new java.awt.Color(41, 33, 44));
        menuName2.setText("menuName2");
        menuName2.setName("menuName2"); // NOI18N
        getContentPane().add(menuName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 620, 150, 50));

        menuName3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        menuName3.setForeground(new java.awt.Color(41, 33, 44));
        menuName3.setText("menuName3");
        menuName3.setName("menuName3"); // NOI18N
        getContentPane().add(menuName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 620, 160, 50));

        menuDesc2.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        menuDesc2.setForeground(new java.awt.Color(41, 33, 44));
        menuDesc2.setText("menuDesc2");
        menuDesc2.setName("menuDesc2"); // NOI18N
        getContentPane().add(menuDesc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 640, 160, 50));

        menuDesc3.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        menuDesc3.setForeground(new java.awt.Color(41, 33, 44));
        menuDesc3.setText("menuDesc3");
        menuDesc3.setName("menuDesc3"); // NOI18N
        getContentPane().add(menuDesc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 640, 160, 50));

        menuPrice1.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        menuPrice1.setForeground(new java.awt.Color(41, 33, 44));
        menuPrice1.setText("menuPrice1");
        menuPrice1.setName("menuPrice1"); // NOI18N
        getContentPane().add(menuPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 680, 140, 50));

        menuBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ItemsMenuBackground.png"))); // NOI18N
        menuBackground1.setName("menuBackground1"); // NOI18N
        menuBackground1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBackground1MouseClicked(evt);
            }
        });
        getContentPane().add(menuBackground1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, -1, -1));

        menuBackground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ItemsMenuBackground.png"))); // NOI18N
        menuBackground2.setName("menuBackground2"); // NOI18N
        menuBackground2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBackground2MouseClicked(evt);
            }
        });
        getContentPane().add(menuBackground2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, -1, -1));

        menuBackground3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ItemsMenuBackground.png"))); // NOI18N
        menuBackground3.setName("menuBackground3"); // NOI18N
        menuBackground3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBackground3MouseClicked(evt);
            }
        });
        getContentPane().add(menuBackground3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UserProfile.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        checkoutQty1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        checkoutQty1.setForeground(new java.awt.Color(196, 16, 21));
        checkoutQty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkoutQty1.setText("0");
        checkoutQty1.setFocusTraversalPolicyProvider(true);
        checkoutQty1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        checkoutQty1.setName("checkoutQty1"); // NOI18N
        getContentPane().add(checkoutQty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 260, 50, 30));

        checkoutQty2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        checkoutQty2.setForeground(new java.awt.Color(196, 16, 21));
        checkoutQty2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkoutQty2.setText("0");
        checkoutQty2.setFocusTraversalPolicyProvider(true);
        checkoutQty2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        checkoutQty2.setName("checkoutQty2"); // NOI18N
        getContentPane().add(checkoutQty2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 400, 50, 30));

        checkoutTotalPriceLabel.setFont(new java.awt.Font("Poppins", 1, 28)); // NOI18N
        checkoutTotalPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        checkoutTotalPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        checkoutTotalPriceLabel.setText("Rp 100k");
        checkoutTotalPriceLabel.setName("checkoutTotalPriceLabel"); // NOI18N
        getContentPane().add(checkoutTotalPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 620, 290, 50));

        checkoutTotalLabel.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        checkoutTotalLabel.setForeground(new java.awt.Color(255, 255, 255));
        checkoutTotalLabel.setText("Total");
        getContentPane().add(checkoutTotalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 620, 50, 50));

        checkoutIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ItemsCheckoutIcon.png"))); // NOI18N
        checkoutIcon1.setName("checkoutIcon1"); // NOI18N
        getContentPane().add(checkoutIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 220, -1, -1));

        checkoutIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ItemsCheckoutIcon.png"))); // NOI18N
        checkoutIcon2.setName("checkoutIcon2"); // NOI18N
        getContentPane().add(checkoutIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 360, -1, -1));

        checkoutName1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        checkoutName1.setForeground(new java.awt.Color(41, 33, 44));
        checkoutName1.setText("checkoutName1");
        checkoutName1.setName("checkoutName1"); // NOI18N
        getContentPane().add(checkoutName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 220, 210, 50));

        checkoutName2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        checkoutName2.setForeground(new java.awt.Color(41, 33, 44));
        checkoutName2.setText("checkoutName2");
        checkoutName2.setName("checkoutName2"); // NOI18N
        getContentPane().add(checkoutName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 360, 210, 50));

        checkoutPrice1.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        checkoutPrice1.setForeground(new java.awt.Color(41, 33, 44));
        checkoutPrice1.setText("checkoutPrice1");
        checkoutPrice1.setName("checkoutPrice1"); // NOI18N
        getContentPane().add(checkoutPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 250, 110, 50));

        checkoutPrice2.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        checkoutPrice2.setForeground(new java.awt.Color(41, 33, 44));
        checkoutPrice2.setText("checkoutPrice2");
        checkoutPrice2.setName("checkoutPrice2"); // NOI18N
        getContentPane().add(checkoutPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 390, 110, 50));

        checkoutBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundItemsCheckout.png"))); // NOI18N
        checkoutBackground1.setName("checkoutBackground1"); // NOI18N
        getContentPane().add(checkoutBackground1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 200, -1, -1));

        checkoutBackground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundItemsCheckout.png"))); // NOI18N
        checkoutBackground2.setName("checkoutBackground2"); // NOI18N
        getContentPane().add(checkoutBackground2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 340, -1, -1));

        backgroundMainDasboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundDashboard.png"))); // NOI18N
        getContentPane().add(backgroundMainDasboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButton1ActionPerformed
        // TODO add your handling code here:
        changeActiveButtonSend(1);
    }//GEN-LAST:event_menuButton1ActionPerformed

    private void menuButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButton2ActionPerformed
        // TODO add your handling code here:
        changeActiveButtonSend(2);
    }//GEN-LAST:event_menuButton2ActionPerformed

    private void menuButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButton3ActionPerformed
        // TODO add your handling code here:
        changeActiveButtonSend(3);
    }//GEN-LAST:event_menuButton3ActionPerformed

    private void menuButtonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonPrevActionPerformed
        // TODO add your handling code here:
        if(currentPages > 1) {
            currentPages = (currentPages - 1);
        }
    }//GEN-LAST:event_menuButtonPrevActionPerformed

    private void menuButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonNextActionPerformed
        // TODO add your handling code here:
        if(currentPages < totalPages) {
            currentPages = (currentPages + 1);
        }
    }//GEN-LAST:event_menuButtonNextActionPerformed

    private void menuBackground3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBackground3MouseClicked
        // TODO add your handling code here:
        // Memperbarui menu yang dipilih dalam proses checkout
        menuSelected = updateCheckout(
                menuSelected,
                menuId.get(2),
                currentCheckoutPages, 
                componentSearch,
                checkoutButtonPrev,
                checkoutButtonNext
        );
        Notifications.getInstance().show(Notifications.Type.INFO, Notifications.Location.TOP_CENTER, "Item Telah Ditambahkan");
    }//GEN-LAST:event_menuBackground3MouseClicked

    private void menuBackground2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBackground2MouseClicked
        // TODO add your handling code here:
        // Memperbarui menu yang dipilih dalam proses checkout
        menuSelected = updateCheckout(
                menuSelected,
                menuId.get(1),
                currentCheckoutPages, 
                componentSearch,
                checkoutButtonPrev,
                checkoutButtonNext
        );
        Notifications.getInstance().show(Notifications.Type.INFO, Notifications.Location.TOP_CENTER, "Item Telah Ditambahkan");
    }//GEN-LAST:event_menuBackground2MouseClicked

    private void menuBackground1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBackground1MouseClicked
        // TODO add your handling code here:
        // Memperbarui menu yang dipilih dalam proses checkout
        menuSelected = updateCheckout(
                menuSelected,
                menuId.get(0),
                currentCheckoutPages, 
                componentSearch,
                checkoutButtonPrev,
                checkoutButtonNext
        );
        Notifications.getInstance().show(Notifications.Type.INFO, Notifications.Location.TOP_CENTER, "Item Telah Ditambahkan");
    }//GEN-LAST:event_menuBackground1MouseClicked

    private void checkoutButtonNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkoutButtonNextMouseClicked
        // TODO add your handling code here:
        // Menambahkan 1 pada CurrentCheckoutPages
        currentCheckoutPages = (currentCheckoutPages + 1);

        // Memperbarui Menu Yang Dicheckout dengan 0, CurrentCheckoutPages, DB, ComponentSearch, CheckoutButtonPrev, dan CheckoutButtonNext
        menuSelected = updateCheckout(
                menuSelected,
                0,
                currentCheckoutPages,
                componentSearch,
                checkoutButtonPrev,
                checkoutButtonNext
        );

        // Mengelompokkan Menu Yang Dicheckout dalam List<Map<Integer, Integer>> Menggunakan CheckoutGrouping
        List<Map<Integer, Integer>> checkoutSelectedMenuGrouping = new CheckoutGrouping().Group(ArrayCounter.countElements(menuSelected));

        // Mengurangi 1 dari CurrentCheckoutPages jika melebihi ukuran (checkoutSelectedMenuGrouping.size() - 1)
        if (currentCheckoutPages > (checkoutSelectedMenuGrouping.size() - 1)) {
            currentCheckoutPages = (currentCheckoutPages - 1);
        }
    }//GEN-LAST:event_checkoutButtonNextMouseClicked

    private void menuButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuButton5ActionPerformed

    private void checkoutButtonPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkoutButtonPrevMouseClicked
        // TODO add your handling code here:
        // Jika CurrentCheckoutPages lebih besar dari 0
        if (currentCheckoutPages > 0) {
            // Mengurangi 1 dari CurrentCheckoutPages
            currentCheckoutPages = (currentCheckoutPages - 1);
            // Memperbarui menu yang dipilih dalam proses checkout
            menuSelected = updateCheckout(
                    menuSelected,
                    0,
                    currentCheckoutPages,
                    componentSearch,
                    checkoutButtonPrev,
                    checkoutButtonNext
            );
        }
    }//GEN-LAST:event_checkoutButtonPrevMouseClicked

    private void menuButtonPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuButtonPrevMouseClicked
        // TODO add your handling code here:
        // Mengurangi 1 dari CurrentPages jika CurrentPages lebih dari 0
        if (currentPages > 0) {
            currentPages = (currentPages - 1);
        }

        // Memperbarui Menu dengan Halaman dan KategoriSaatIni
        menuId = MenuUpdater.updateMenu(
                componentSearch,
                currentMenuCategories,
                currentPages,
                menuButtonNext,
                menuButtonPrev
        );
    }//GEN-LAST:event_menuButtonPrevMouseClicked

    private void menuButtonNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuButtonNextMouseClicked
        // TODO add your handling code here:
        // Menambahkan 1 pada HalamanSaatIni
        currentPages = currentPages + 1;

        // Memperbarui Menu dengan Halaman dan KategoriSaatIni
        menuId = MenuUpdater.updateMenu(
                componentSearch,
                currentMenuCategories,
                currentPages,
                menuButtonNext,
                menuButtonPrev
        );

        // Mendapatkan Semua ID Menu dari KategoriSaatIni
        int[] allMenuIds = db.getMenuIds(currentMenuCategories);
//
        // Mengelompokkan ID Menu dalam List<List<Integer>>
        List<List<Integer>> menuGrouping = MenuGrouping.groupArray(allMenuIds);

        // Mengurangi 1 dari HalamanSaatIni jika sudah mencapai HalamanTerakhir
        if (currentPages >= menuGrouping.size() - 1) {
            currentPages = currentPages - 1;
        }
    }//GEN-LAST:event_menuButtonNextMouseClicked

    private void menuButtonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuButtonLoginMouseClicked
        // TODO add your handling code here:
        // Mendapatkan Posisi Tengah untuk Menempatkan Halaman Loading di Posisi Tengah
        Point centerPoint = Screen.getCenterPoint();

        // Mengalihkan ke Halaman Login dan Mengatur Halaman Loading di Posisi Tengah
        Loading loadingPage = new Loading("Login", false);
        loadingPage.setLocation(centerPoint.x - loadingPage.getWidth() / 2, centerPoint.y - loadingPage.getHeight() / 2);
        loadingPage.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuButtonLoginMouseClicked

    private void buttonCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCheckoutMouseClicked
        // TODO add your handling code here:
        if(userAuthLoginId == 0) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_CENTER, "Kamu Belum Login Nih, Login Dulu Yuk!");
            return;
        }
        if(menuSelected.length < 1) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_CENTER, "Kamu Pilih Menu Nih, Pilih Dulu Yuk!");
            return;
        }
        
        // Menghitung Menu yang Dipilih
        Map<Integer, Integer> countingMenuSelected = ArrayCounter.countElements(menuSelected);

        // Mendapatkan Posisi Tengah untuk Menempatkan Halaman Loading di Posisi Tengah
        Point centerPoint = Screen.getCenterPoint();

        // Mengalihkan ke Halaman Payment Gateway dan Mengatur Halaman Loading di Posisi Tengah
        Loading loadingPage = new Loading("PaymentGateway", false);
        loadingPage.setUserId(this.userAuthLoginId);
        loadingPage.setCheckoutList(countingMenuSelected);
        loadingPage.setLocation(centerPoint.x - loadingPage.getWidth() / 2, centerPoint.y - loadingPage.getHeight() / 2);
        loadingPage.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonCheckoutMouseClicked

    private void menuButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuButton5MouseClicked
        // TODO add your handling code here:
        Point centerPoint = Screen.getCenterPoint();
        Loading Loading = new Loading("History", false);
        Loading.setUserId(this.userAuthLoginId);
        Loading.setLocation(centerPoint.x - Loading.getWidth() / 2, centerPoint.y - Loading.getHeight() / 2);
        Loading.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Dashboard(0).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundMainDasboard;
    private Functions.Dashboard.MenuButtonClass buttonCheckout;
    private javax.swing.JLabel checkoutBackground1;
    private javax.swing.JLabel checkoutBackground2;
    private Functions.Dashboard.MenuButtonClass checkoutButtonNext;
    private Functions.Dashboard.MenuButtonClass checkoutButtonPrev;
    private javax.swing.JLabel checkoutIcon1;
    private javax.swing.JLabel checkoutIcon2;
    private javax.swing.JLabel checkoutName1;
    private javax.swing.JLabel checkoutName2;
    private javax.swing.JLabel checkoutPrice1;
    private javax.swing.JLabel checkoutPrice2;
    private javax.swing.JLabel checkoutQty1;
    private javax.swing.JLabel checkoutQty2;
    private javax.swing.JLabel checkoutTotalLabel;
    private javax.swing.JLabel checkoutTotalPriceLabel;
    private javax.swing.JLabel daftarMenuLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel menuBackground1;
    private javax.swing.JLabel menuBackground2;
    private javax.swing.JLabel menuBackground3;
    private Functions.Dashboard.MenuButtonClass menuButton1;
    private Functions.Dashboard.MenuButtonClass menuButton2;
    private Functions.Dashboard.MenuButtonClass menuButton3;
    private Functions.Dashboard.MenuButtonClass menuButton5;
    private Functions.Dashboard.MenuButtonClass menuButtonLogin;
    private Functions.Dashboard.MenuButtonClass menuButtonNext;
    private Functions.Dashboard.MenuButtonClass menuButtonPrev;
    private javax.swing.JLabel menuDesc1;
    private javax.swing.JLabel menuDesc2;
    private javax.swing.JLabel menuDesc3;
    private javax.swing.JLabel menuIcon1;
    private javax.swing.JLabel menuIcon2;
    private javax.swing.JLabel menuIcon3;
    private javax.swing.JLabel menuName1;
    private javax.swing.JLabel menuName2;
    private javax.swing.JLabel menuName3;
    private javax.swing.JLabel menuPrice1;
    private javax.swing.JLabel menuPrice2;
    private javax.swing.JLabel menuPrice3;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
