/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Components.Table.TableCustom;
import Functions.MySQL.Database;
import Functions.Utils.Screen;
import com.fasterxml.jackson.core.JsonFactory;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.awt.Point;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dxrry
 */
public class History extends javax.swing.JFrame {
    
    private Integer userAuthLoginId = 0;
    private Integer selectedOrderID = 0;

    /**
     * Creates new form NewJFrame
     * @param userAuthLoginId
     */
    public History(Integer userAuthLoginId) {
        initComponents();
        this.userAuthLoginId = userAuthLoginId;
        
        
        // Disable Editable
        jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object [][] {
            },
            new String [] {
                "Order ID", "Pembelian", "Pembayaran", "Tanggal", "Status"
            }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        });
        TableCustom.apply(jScrollPane1, TableCustom.TableType.DEFAULT);
        fillTable(jTable1);
        jTable1.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            String getOrderID = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            String removeUnusedOrderID = getOrderID.replaceAll("FIVE[0-9]{0,99}DRAGONS", "");
            History.this.selectedOrderID = Integer.valueOf(removeUnusedOrderID);
        });
        
    }
    
    private void fillTable(JTable table) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        Database db = new Database();
        List<Functions.Types.History> fullname = db.getAllHistory(this.userAuthLoginId);
        
        // Menampilkan semua riwayat
        for (Functions.Types.History history : fullname) {
            // Format timestamp menjadi format yang diinginkan
            DateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            DateFormat outputFormat = new SimpleDateFormat("dd MMMM yyyy, HH:mm");

            try {
                Date date = inputFormat.parse(history.getDate());
                String formattedTimestamp = outputFormat.format(date);
                
                String getMenuSelected = history.getMenuSelected();
                JsonFactory jsonFactory = new JsonFactory();
                ObjectMapper objectMapper = new ObjectMapper(jsonFactory);

                try {
                    JsonNode jsonNode = objectMapper.readTree(getMenuSelected);
                    if (jsonNode.isObject()) {
                        String orderID = ("FIVE" + history.getUserID() + "DRAGONS" + history.getHistoryID());
                        String orderStatus = history.getStatus();
                        String orderDate = formattedTimestamp;
                        String orderPaymentMethode = history.getPaymentMethode() + " Transfer";
                        String orderPaymentName = history.getPaymentName();
                        String orderDesc = ("Pembelian " + jsonNode.size() + "x Items");
                        
                        model.addRow(new Object[]{orderID, orderDesc, orderPaymentMethode, orderDate, orderStatus});
                    }
                } catch (IOException ex) {
                    System.out.println(ex);
                }

                
            } catch (java.text.ParseException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button2 = new Components.Button();
        button1 = new Components.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button2.setBackground(new java.awt.Color(255, 189, 36));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setText("Kembali Ke Halaman Utama");
        button2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        button2.setRound(30);
        button2.setShadowColor(new java.awt.Color(0, 0, 0));
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 670, 430, 70));

        button1.setBackground(new java.awt.Color(255, 189, 36));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Lihat Data");
        button1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        button1.setRound(30);
        button1.setShadowColor(new java.awt.Color(0, 0, 0));
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 670, 760, 70));

        jTable1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "1", "1", null, null}
            },
            new String [] {
                "Order ID", "Pembelian", "Pembayaran", "Tanggal", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 1180, 330));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundHistoryOrder.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        // TODO add your handling code here:
        if(selectedOrderID != 0) {
            Point centerPoint = Screen.getCenterPoint();
        
            Loading Loading = new Loading("DetailOrder", this.selectedOrderID);
            Loading.setUserId(userAuthLoginId);
            Loading.setLocation(centerPoint.x - Loading.getWidth() / 2, centerPoint.y - Loading.getHeight() / 2);
            Loading.setVisible(true);
            dispose();
        }   
    }//GEN-LAST:event_button1MouseClicked

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked
        // TODO add your handling code here:
        Point centerPoint = Screen.getCenterPoint();
        
        Loading Loading = new Loading("Dashboard", this.selectedOrderID);
        Loading.setUserId(userAuthLoginId);
        Loading.setLocation(centerPoint.x - Loading.getWidth() / 2, centerPoint.y - Loading.getHeight() / 2);
        Loading.setVisible(true);
        dispose();
    }//GEN-LAST:event_button2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new History(1).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.Button button1;
    private Components.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
