/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Functions.MySQL.Database;
import Functions.Utils.GUIHelper;
import Functions.Utils.Screen;
import java.awt.Point;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author dxrry
 */
public class Payment extends javax.swing.JFrame {
    
    private final Map<Integer, Integer> checkoutList;
    private String paymentMethod = "GOPAY";
    private Integer userAuthLoginId = 0;
    private final Database db = new Database();
    
    /**
     * Creates new form MainPayment
     * @param userAuthLoginId
     * @param checkoutList
     * @param paymentMethod
     */
    public Payment(Integer userAuthLoginId, Map<Integer, Integer> checkoutList, String paymentMethod) {
        initComponents();
        this.userAuthLoginId = userAuthLoginId;
        this.checkoutList = checkoutList;
        this.paymentMethod = paymentMethod;
        
        Integer calculatePrice = calculateTotalPrice(db, (Map<Integer, Integer>) this.checkoutList);
        buttonNominal.setText(GUIHelper.priceIdr(calculatePrice));
        buttonPembayaranTerpilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Payments/" + paymentMethod + ".png")));
        buttonNomorRekening.setText(db.getPaymentNumber(paymentMethod));
    }
    
    private static Integer calculateTotalPrice(Database db, Map<Integer, Integer> counter) {
        Integer totalPrice = 0;
        for (Map.Entry<Integer, Integer> entry : counter.entrySet()) {
            Integer menuId = entry.getKey();
            Integer quantity = entry.getValue();
            Integer menuPrice = db.getMenuPrice(menuId);
            totalPrice += menuPrice * quantity;
        }
        return totalPrice;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonNomorRekening = new Components.Button();
        buttonPembayaranTerpilih = new Components.Button();
        buttonNominal = new Components.Button();
        buttonNext = new Components.Button();
        fieldAtasNama = new Components.TextField();
        labelTransfer = new javax.swing.JLabel();
        labelAtasNama = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonNomorRekening.setBackground(new java.awt.Color(255, 189, 36));
        buttonNomorRekening.setForeground(new java.awt.Color(255, 255, 255));
        buttonNomorRekening.setText("085883887825");
        buttonNomorRekening.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        buttonNomorRekening.setRound(30);
        buttonNomorRekening.setShadowColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(buttonNomorRekening, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 310, 340, 90));

        buttonPembayaranTerpilih.setBackground(new java.awt.Color(255, 189, 36));
        buttonPembayaranTerpilih.setForeground(new java.awt.Color(255, 255, 255));
        buttonPembayaranTerpilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Payments/GOPAY.png"))); // NOI18N
        buttonPembayaranTerpilih.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        buttonPembayaranTerpilih.setRound(30);
        buttonPembayaranTerpilih.setShadowColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(buttonPembayaranTerpilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 340, 90));

        buttonNominal.setBackground(new java.awt.Color(255, 189, 36));
        buttonNominal.setForeground(new java.awt.Color(255, 255, 255));
        buttonNominal.setText("Rp 400.000,-");
        buttonNominal.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        buttonNominal.setRound(30);
        buttonNominal.setShadowColor(new java.awt.Color(0, 0, 0));
        buttonNominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNominalActionPerformed(evt);
            }
        });
        getContentPane().add(buttonNominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 690, 70));

        buttonNext.setBackground(new java.awt.Color(255, 189, 36));
        buttonNext.setForeground(new java.awt.Color(255, 255, 255));
        buttonNext.setText("Buat Orderan");
        buttonNext.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        buttonNext.setRound(30);
        buttonNext.setShadowColor(new java.awt.Color(0, 0, 0));
        buttonNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNextMouseClicked(evt);
            }
        });
        getContentPane().add(buttonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 680, 690, 70));

        fieldAtasNama.setForeground(new java.awt.Color(0, 0, 0));
        fieldAtasNama.setText("Atas Nama Bank Kamu");
        fieldAtasNama.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        fieldAtasNama.setRound(30);
        fieldAtasNama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldAtasNamaMouseClicked(evt);
            }
        });
        getContentPane().add(fieldAtasNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 580, 690, 70));

        labelTransfer.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        labelTransfer.setForeground(new java.awt.Color(255, 255, 255));
        labelTransfer.setText("Silahkan Lakukan Pembayaran Dengan Nominal");
        getContentPane().add(labelTransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, -1, -1));

        labelAtasNama.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        labelAtasNama.setForeground(new java.awt.Color(255, 255, 255));
        labelAtasNama.setText(" Atas Nama Kamu");
        getContentPane().add(labelAtasNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundPayment.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNominalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonNominalActionPerformed

    private void buttonNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNextMouseClicked
        // TODO add your handling code here:
        db.putOrderHistory(checkoutList, this.paymentMethod, fieldAtasNama.getText(), this.userAuthLoginId);
        Point centerPoint = Screen.getCenterPoint();
        Loading Loading = new Loading("History", false);
        Loading.setUserId(this.userAuthLoginId);
        Loading.setLocation(centerPoint.x - Loading.getWidth() / 2, centerPoint.y - Loading.getHeight() / 2);
        Loading.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonNextMouseClicked

    private void fieldAtasNamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldAtasNamaMouseClicked
        // TODO add your handling code here:
        fieldAtasNama.setText("");
    }//GEN-LAST:event_fieldAtasNamaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Payment(1, new HashMap<>(), "OVO").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.Button buttonNext;
    private Components.Button buttonNominal;
    private Components.Button buttonNomorRekening;
    private Components.Button buttonPembayaranTerpilih;
    private Components.TextField fieldAtasNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelAtasNama;
    private javax.swing.JLabel labelTransfer;
    // End of variables declaration//GEN-END:variables
}
