/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
import Components.Toast.Notifications;
import Functions.MySQL.Database;
import Functions.Utils.MD5Utils;
import Functions.Utils.Screen;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author dxrry
 */
public class Register extends javax.swing.JFrame {
    
    private Components.TextField[] textFieldsList;

    /**
     * Creates new form Login
     */
    public Register() {
        initComponents();
        FlatLaf.registerCustomDefaultsSource("Components.Toast");
        FlatIntelliJLaf.setup();
        Notifications.getInstance().setJFrame(this);
        setFieldsPlaceholder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void setFieldsPlaceholder() {
        textFieldsList = new Components.TextField[4];
        textFieldsList[0] = fieldName;
        textFieldsList[1] = fieldUsername;
        textFieldsList[2] = fieldNumber;
        textFieldsList[3] = fieldEmail;
        
        for (Components.TextField fields : textFieldsList) {
            fields.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    fields.setText("");
                }
            });
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonRegister = new Components.Button();
        fieldUsername = new Components.TextField();
        fieldNumber = new Components.TextField();
        fieldEmail = new Components.TextField();
        fieldName = new Components.TextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonLogin = new Components.Button();
        fieldPassword = new Components.FieldPassword();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonRegister.setBackground(new java.awt.Color(255, 189, 36));
        buttonRegister.setForeground(new java.awt.Color(255, 255, 255));
        buttonRegister.setText("Register");
        buttonRegister.setAutoscrolls(true);
        buttonRegister.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        buttonRegister.setRound(30);
        buttonRegister.setShadowColor(new java.awt.Color(0, 0, 0));
        buttonRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRegisterMouseClicked(evt);
            }
        });
        getContentPane().add(buttonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 670, 320, 70));

        fieldUsername.setForeground(new java.awt.Color(0, 0, 0));
        fieldUsername.setText("johndoe");
        fieldUsername.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        fieldUsername.setName("fieldUsername"); // NOI18N
        fieldUsername.setRound(30);
        fieldUsername.setShadowColor(new java.awt.Color(0, 0, 0));
        fieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(fieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 320, 320, 70));

        fieldNumber.setForeground(new java.awt.Color(0, 0, 0));
        fieldNumber.setText("08123456789");
        fieldNumber.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        fieldNumber.setName("fieldNumber"); // NOI18N
        fieldNumber.setRound(30);
        fieldNumber.setShadowColor(new java.awt.Color(0, 0, 0));
        fieldNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNumberActionPerformed(evt);
            }
        });
        getContentPane().add(fieldNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 440, 320, 70));

        fieldEmail.setForeground(new java.awt.Color(0, 0, 0));
        fieldEmail.setText("example@gmail.com");
        fieldEmail.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        fieldEmail.setName("fieldEmail"); // NOI18N
        fieldEmail.setRound(30);
        fieldEmail.setShadowColor(new java.awt.Color(0, 0, 0));
        fieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailActionPerformed(evt);
            }
        });
        getContentPane().add(fieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 320, 70));

        fieldName.setForeground(new java.awt.Color(0, 0, 0));
        fieldName.setText("John Doe");
        fieldName.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        fieldName.setName("fieldName"); // NOI18N
        fieldName.setRound(30);
        fieldName.setShadowColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 320, 70));

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Username");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, -1, -1));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, -1, -1));

        buttonLogin.setBackground(new java.awt.Color(255, 189, 36));
        buttonLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin.setText("Back to Log In");
        buttonLogin.setAutoscrolls(true);
        buttonLogin.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        buttonLogin.setRound(30);
        buttonLogin.setShadowColor(new java.awt.Color(0, 0, 0));
        buttonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLoginMouseClicked(evt);
            }
        });
        getContentPane().add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 670, 320, 70));

        fieldPassword.setForeground(new java.awt.Color(0, 0, 0));
        fieldPassword.setText("ExamplePasswordDefault1337");
        fieldPassword.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        fieldPassword.setRound(30);
        fieldPassword.setShadowColor(new java.awt.Color(0, 0, 0));
        fieldPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 650, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackgroundRegister.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailActionPerformed

    private void fieldNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNumberActionPerformed

    private void fieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUsernameActionPerformed

    private void buttonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginMouseClicked
        // TODO add your handling code here:
        
        Point centerPoint = Screen.getCenterPoint();
        Loading Loading = new Loading("Login", false);
        Loading.setLocation(centerPoint.x - Loading.getWidth() / 2, centerPoint.y - Loading.getHeight() / 2);
        Loading.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonLoginMouseClicked

    private void buttonRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRegisterMouseClicked
        // TODO add your handling code here:
        char[] passwordChars = fieldPassword.getPassword();
        String password = new String(passwordChars);
        
        for (Components.TextField fields : textFieldsList) {
            if(password.equals("") || fields.getText().equals("")) {
                Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_CENTER, "Ada Data Yang Masih Kosong Nih, Cek Lagi Yuk!");
                return;
            }
        }
        String md5Hash = MD5Utils.calculateMD5(password);
        Database db = new Database();
        
        Integer checkIsUserRegistered = db.getUserId(fieldUsername.getText());
        if(checkIsUserRegistered != 0) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_CENTER, "Username Telah Terdaftar");
        }else{
            db.putNewAccount(fieldName.getText(), 
                fieldUsername.getText(),
                md5Hash,
                fieldNumber.getText(),
                fieldEmail.getText()
            );
            checkIsUserRegistered = db.getUserId(fieldUsername.getText());
            if(checkIsUserRegistered != 0) {
                Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER, "Yeay! Akun Mu Telah Terdaftar");
            }else{
                Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_CENTER, "Ada Masalah Saat Registrasi");
            }
        }
    }//GEN-LAST:event_buttonRegisterMouseClicked

    private void fieldPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldPasswordMouseClicked
        // TODO add your handling code here:
        fieldPassword.setText("");
    }//GEN-LAST:event_fieldPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Register().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.Button buttonLogin;
    private Components.Button buttonRegister;
    private Components.TextField fieldEmail;
    private Components.TextField fieldName;
    private Components.TextField fieldNumber;
    private Components.FieldPassword fieldPassword;
    private Components.TextField fieldUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
